<a href="https://colab.research.google.com/github/sd3ph/python-random-quote/blob/master/Python_Tutorial_Dutta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
print("Hi")  # Print a Text


Hi


In [33]:
a =2.0   # Print a variable
print(a)

2.0


In [41]:
for i in range(1,5):   # A do loop in the range 1 and 5
 print(i)

1
2
3
4


In [42]:
for i in range(1,5):    # nested Do loop
  for j in range(1,5):
    print(i,j)

1 1
1 2
1 3
1 4
2 1
2 2
2 3
2 4
3 1
3 2
3 3
3 4
4 1
4 2
4 3
4 4


In [43]:
a = 2.0
b = 5.0
a+b       # variable addition

7.0

In [44]:
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)      # Do loop using texts

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


In [46]:
a = [1,0,0]    # Defining a matrix
a

[1, 0, 0]

In [52]:
import numpy as np    # Adapting Numpy library
A = np.array([1,2,3])  # Defining array using Numpy style
print(A)

[1 2 3]


In [53]:
B = np.array([1,2,3])
print(B)

[1 2 3]


In [54]:
C=A+B     # Matrix addition using numpy
print(C)

[2 4 6]


In [59]:
D=np.array([[1,2,3],
   [4,5,6],
   [7,8,9]])
print(D.transpose()) # Transpose of a three dimensional matrix C using Numpy

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [68]:
print(D[0,:]) # Printing 0th row
print(D[:,0]) # Printing 0th column

[1 2 3]
[1 4 7]


In [76]:
c1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
c2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
c3 = c1 @ c2  # Matrix Multiplication using Numpy
print(c3)


[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [104]:
import matplotlib.pyplot as suman

In [89]:
import math 
a = math.pi / 6
     
# returning the value of sine of pi / 6 
print ("The value of sine of pi / 6 is : ", end ="") 
print (math.sin(a)) 

The value of sine of pi / 6 is : 0.49999999999999994


In [96]:
import pandas  # Import library of Panda